### ISSUE TITLE
Is this project alive?

### ISSUE THREAD

**Issue by rusefillc** [seancfoley/mjvmk#1]
Does this project support GCC? Any plans to add Makefile?

Any reference configurations for anything ARM?

**Comment by seancfoley** [comment]
Hello.  At this time the project is built with MS Visual Studio.  When I added it to github about 5 years ago, I ensured that it could be built with the MS Visual Studio version available at the time.  Most likely it could be ported to use gcc instead.  No, it does not have an ARM reference configuration, just x86 at this time.  Also, it supports an earlier version of Java, so a bit of work would be required to support later versions.
